-- PROPOSED seed (lives in proposed/ on purpose: NOT part of the numbered migration sequence and not applied automatically), derived by script from the draft normalization map of five
-- SSES/POF GLs (C1, C2, C7, C9, centralized). NOT owner-approved: review every
-- row before merging. Rules used: sub heads with >=5 rows across those GLs
-- (115 heads, ~97% of classified rows); rarer sub heads and raw main heads
-- such as 'Misscilinieus' / 'Repair and mantainance' are deliberately left
-- unmapped (they belong in review, not silently merged). Bank-side rows
-- (Cash at bank, Bank Account) are not heads: bank is a column, not a head.

insert into public.account_heads (main_head, sub_head) values
    ('Accrued and Other Liabilities', 'CPF'),
    ('Accrued and Other Liabilities', 'CPF Payable'),
    ('Accrued and Other Liabilities', 'Employees'' Old Age Benefit Institution Payable'),
    ('Accrued and Other Liabilities', 'EOBI'),
    ('Accrued and Other Liabilities', 'EOBI Payable'),
    ('Accrued and Other Liabilities', 'Fee Refund'),
    ('Accrued and Other Liabilities', 'Guard Salary'),
    ('Accrued and Other Liabilities', 'IBFT From Other Campuses'),
    ('Accrued and Other Liabilities', 'Income Tax Exp'),
    ('Accrued and Other Liabilities', 'Inter-Campus Loan Payable'),
    ('Accrued and Other Liabilities', 'PESSI'),
    ('Accrued and Other Liabilities', 'PESSI Payable'),
    ('Accrued and Other Liabilities', 'Salaries'),
    ('Accrued and Other Liabilities', 'Salaries Payable'),
    ('Accrued and Other Liabilities', 'Security Deposit Received (Student)'),
    ('Accrued and Other Liabilities', 'Security Deposit Refund (Staff/Student)'),
    ('Accrued and Other Liabilities', 'Security Deposit Refund (Student)'),
    ('Accrued and Other Liabilities', 'Security Deposit Refundable'),
    ('Accrued and Other Liabilities', 'Security Deposits Refundable'),
    ('Accrued and Other Liabilities', 'Security Guard'),
    ('Accrued and Other Liabilities', 'Society Share'),
    ('Accrued and Other Liabilities', 'Society Share (Expense Leg)'),
    ('Accrued and Other Liabilities', 'Society Share Payable'),
    ('Accrued and Other Liabilities', 'Staff Final Settlement Payable'),
    ('Accrued and Other Liabilities', 'Staff Income Tax (Expense Leg)'),
    ('Accrued and Other Liabilities', 'Statutory Dues Payable - Wht/Income Tax'),
    ('Accrued and Other Liabilities', 'Student Security Deposit Payable'),
    ('Accrued and Other Liabilities', 'Student Security Deposits Payable'),
    ('Accrued and Other Liabilities', 'Utility'),
    ('Accrued and Other Liabilities', 'Withholding Tax/Income Tax Payable'),
    ('Assets', '(bank-side)'),
    ('Assets', 'Advance Tax'),
    ('Assets', 'Fees & Funds Receivable'),
    ('Assets', 'Inter-Account Transfer (From Pls Account)'),
    ('Assets', 'Inter-Bank Transfer'),
    ('Assets', 'Inter-Campus Loan Receivable'),
    ('Assets', 'Inter-Entity Loan Receivable - Nasheeman'),
    ('Assets', 'Receivable from SSES Head Office'),
    ('Expenses', 'Advertising Expense'),
    ('Expenses', 'Affiliation & Registration Fees'),
    ('Expenses', 'Bank Charges'),
    ('Expenses', 'Bus Hire'),
    ('Expenses', 'CPF'),
    ('Expenses', 'CPF Contribution'),
    ('Expenses', 'Electricity'),
    ('Expenses', 'Electricity Expense'),
    ('Expenses', 'EOBI'),
    ('Expenses', 'EOBI Contribution'),
    ('Expenses', 'Events & Functions'),
    ('Expenses', 'Events & Training Expense'),
    ('Expenses', 'Final Payment'),
    ('Expenses', 'Fuel Charges'),
    ('Expenses', 'Grants & Staff Welfare Payments'),
    ('Expenses', 'Income Tax Exp'),
    ('Expenses', 'It & Software Expense'),
    ('Expenses', 'Miscellaneous'),
    ('Expenses', 'Miscelleneous'),
    ('Expenses', 'PESSI'),
    ('Expenses', 'PESSI Contribution'),
    ('Expenses', 'Petty Cash'),
    ('Expenses', 'Petty Cash & Refreshment'),
    ('Expenses', 'Printing & Stationery'),
    ('Expenses', 'Printing Expense'),
    ('Expenses', 'Ptcl/Telephone Expense'),
    ('Expenses', 'Refreshment'),
    ('Expenses', 'Registration & Regulatory Fees'),
    ('Expenses', 'Repair & Maintenance'),
    ('Expenses', 'Repairs & Maintenance'),
    ('Expenses', 'Salaries'),
    ('Expenses', 'Security Guard'),
    ('Expenses', 'Security Guard Salary'),
    ('Expenses', 'Society Share'),
    ('Expenses', 'Staff Final Settlement'),
    ('Expenses', 'Staff Welfare & Grants'),
    ('Expenses', 'Stationery & Printing'),
    ('Expenses', 'Stationery Expense'),
    ('Expenses', 'Sui Gas Charges'),
    ('Expenses', 'Sui Gas Expense'),
    ('Expenses', 'Telephone Bills'),
    ('Expenses', 'Utilities'),
    ('Expenses', 'Utility'),
    ('Expenses', 'Vehicle Fuel & Generator Expense'),
    ('Expenses', 'W.H Tax'),
    ('Expenses', 'Water Expense'),
    ('Income', 'Admission Fee'),
    ('Income', 'Admission Fee Income'),
    ('Income', 'Admission Form Fee'),
    ('Income', 'Admission Form Sales'),
    ('Income', 'Annual Charges'),
    ('Income', 'Annual Charges Income'),
    ('Income', 'Bank Profit'),
    ('Income', 'Bus / Transport Fee'),
    ('Income', 'Bus Fee Income'),
    ('Income', 'Canteen Rent'),
    ('Income', 'Canteen Rent Income'),
    ('Income', 'Fine / Late Fee Income'),
    ('Income', 'Fine Income'),
    ('Income', 'Miscellaneous Income'),
    ('Income', 'Miscellaneous/Installment Income'),
    ('Income', 'Monthly Fee Income'),
    ('Income', 'Monthly Fund Income'),
    ('Income', 'Monthly Funds'),
    ('Income', 'Registration Fee'),
    ('Income', 'Registration Fee Income'),
    ('Income', 'Rent Income'),
    ('Income', 'Security Fee Income'),
    ('Income', 'Tuition Fee (Monthly Fee)'),
    ('Income', 'Tuition Fee Income'),
    ('Income', 'Tuition Fee Recievable'),
    ('Non-Current Assets', 'Building Improvements - Additions'),
    ('Non-Current Assets', 'Work In Progress - Building And Civil Works'),
    ('Requires Clarification', 'Outward Clearing (Inter-Account)'),
    ('Requires Clarification', 'Unidentified Cash Deposit'),
    ('Requires Clarification', 'Unidentified Payment'),
    ('Requires Clarification', 'Unidentified Receipt');

insert into public.account_head_aliases (alias_main, alias_sub, head_id)
select v.alias_main, v.alias_sub, h.id
from (values
    ('accrued and other liabilities', 'cpf', 'Accrued and Other Liabilities', 'CPF'),
    ('accrued and other liabilities', 'cpf payable', 'Accrued and Other Liabilities', 'CPF Payable'),
    ('accrued and other liabilities', 'employees'' old age benefit institution payable', 'Accrued and Other Liabilities', 'Employees'' Old Age Benefit Institution Payable'),
    ('accrued and other liabilities', 'eobi', 'Accrued and Other Liabilities', 'EOBI'),
    ('accrued and other liabilities', 'eobi payable', 'Accrued and Other Liabilities', 'EOBI Payable'),
    ('accrued and other liabilities', 'guard salary', 'Accrued and Other Liabilities', 'Guard Salary'),
    ('accrued and other liabilities', 'income tax exp', 'Accrued and Other Liabilities', 'Income Tax Exp'),
    ('accrued and other liabilities', 'income tax payable', 'Accrued and Other Liabilities', 'Withholding Tax/Income Tax Payable'),
    ('accrued and other liabilities', 'pessi', 'Accrued and Other Liabilities', 'PESSI'),
    ('accrued and other liabilities', 'pessi payable', 'Accrued and Other Liabilities', 'PESSI Payable'),
    ('accrued and other liabilities', 'salaries payable', 'Accrued and Other Liabilities', 'Salaries Payable'),
    ('accrued and other liabilities', 'salary', 'Accrued and Other Liabilities', 'Salaries'),
    ('accrued and other liabilities', 'security deposit received (student)', 'Accrued and Other Liabilities', 'Security Deposit Received (Student)'),
    ('accrued and other liabilities', 'security deposit refund', 'Accrued and Other Liabilities', 'Security Deposit Refundable'),
    ('accrued and other liabilities', 'security deposit refund (staff/student)', 'Accrued and Other Liabilities', 'Security Deposit Refund (Staff/Student)'),
    ('accrued and other liabilities', 'security deposit refund (student)', 'Accrued and Other Liabilities', 'Security Deposit Refund (Student)'),
    ('accrued and other liabilities', 'security deposits refundable', 'Accrued and Other Liabilities', 'Security Deposits Refundable'),
    ('accrued and other liabilities', 'security guard', 'Accrued and Other Liabilities', 'Security Guard'),
    ('accrued and other liabilities', 'security refund payable', 'Accrued and Other Liabilities', 'Security Deposit Refundable'),
    ('accrued and other liabilities', 'society share', 'Accrued and Other Liabilities', 'Society Share'),
    ('accrued and other liabilities', 'society share (expense leg)', 'Accrued and Other Liabilities', 'Society Share (Expense Leg)'),
    ('accrued and other liabilities', 'society share payable', 'Accrued and Other Liabilities', 'Society Share Payable'),
    ('accrued and other liabilities', 'staff final settlement payable', 'Accrued and Other Liabilities', 'Staff Final Settlement Payable'),
    ('accrued and other liabilities', 'staff income tax (expense leg)', 'Accrued and Other Liabilities', 'Staff Income Tax (Expense Leg)'),
    ('accrued and other liabilities', 'statutory dues payable - wht/income tax', 'Accrued and Other Liabilities', 'Statutory Dues Payable - Wht/Income Tax'),
    ('accrued and other liabilities', 'student security deposit payable', 'Accrued and Other Liabilities', 'Student Security Deposit Payable'),
    ('accrued and other liabilities', 'student security deposits payable', 'Accrued and Other Liabilities', 'Student Security Deposits Payable'),
    ('accrued and other liabilities', 'utility', 'Accrued and Other Liabilities', 'Utility'),
    ('accrued and other liabilities', 'wht payable', 'Accrued and Other Liabilities', 'Withholding Tax/Income Tax Payable'),
    ('accrued and other liabilities', 'withholding tax payable', 'Accrued and Other Liabilities', 'Withholding Tax/Income Tax Payable'),
    ('assets', 'fee & funds recievable', 'Assets', 'Fees & Funds Receivable'),
    ('assets', 'fees & funds receivable', 'Assets', 'Fees & Funds Receivable'),
    ('assets', 'inter-account transfer (from pls account)', 'Assets', 'Inter-Account Transfer (From Pls Account)'),
    ('assets', 'inter-bank transfer', 'Assets', 'Inter-Bank Transfer'),
    ('assets', 'inter-campus loan receivable', 'Assets', 'Inter-Campus Loan Receivable'),
    ('assets', 'inter-entity loan receivable - nasheeman', 'Assets', 'Inter-Entity Loan Receivable - Nasheeman'),
    ('assets', 'receivable from head office', 'Assets', 'Receivable from SSES Head Office'),
    ('assets', 'receivable from sses head office', 'Assets', 'Receivable from SSES Head Office'),
    ('current assets', 'advance tax', 'Assets', 'Advance Tax'),
    ('current assets', 'cash at bank', 'Assets', '(bank-side)'),
    ('current assets', 'fee income - receivable', 'Assets', 'Fees & Funds Receivable'),
    ('expenses', 'advertising expense', 'Expenses', 'Advertising Expense'),
    ('expenses', 'affiliation & registration fees', 'Expenses', 'Affiliation & Registration Fees'),
    ('expenses', 'bank charges', 'Expenses', 'Bank Charges'),
    ('expenses', 'bus hire', 'Expenses', 'Bus Hire'),
    ('expenses', 'cpf', 'Expenses', 'CPF'),
    ('expenses', 'cpf contribution', 'Expenses', 'CPF Contribution'),
    ('expenses', 'electricity', 'Expenses', 'Electricity'),
    ('expenses', 'electricity expense', 'Expenses', 'Electricity Expense'),
    ('expenses', 'eobi', 'Expenses', 'EOBI'),
    ('expenses', 'eobi contribution', 'Expenses', 'EOBI Contribution'),
    ('expenses', 'events & functions', 'Expenses', 'Events & Functions'),
    ('expenses', 'events & training expense', 'Expenses', 'Events & Training Expense'),
    ('expenses', 'events and functions', 'Expenses', 'Events & Functions'),
    ('expenses', 'final payment', 'Expenses', 'Final Payment'),
    ('expenses', 'fuel charges', 'Expenses', 'Fuel Charges'),
    ('expenses', 'grants & staff welfare payments', 'Expenses', 'Grants & Staff Welfare Payments'),
    ('expenses', 'income tax exp', 'Expenses', 'Income Tax Exp'),
    ('expenses', 'it & software expense', 'Expenses', 'It & Software Expense'),
    ('expenses', 'miscellaneous', 'Expenses', 'Miscellaneous'),
    ('expenses', 'miscelleneous', 'Expenses', 'Miscelleneous'),
    ('expenses', 'pessi', 'Expenses', 'PESSI'),
    ('expenses', 'pessi contribution', 'Expenses', 'PESSI Contribution'),
    ('expenses', 'petty cash', 'Expenses', 'Petty Cash'),
    ('expenses', 'petty cash & refreshment', 'Expenses', 'Petty Cash & Refreshment'),
    ('expenses', 'printing & stationery', 'Expenses', 'Printing & Stationery'),
    ('expenses', 'printing expense', 'Expenses', 'Printing Expense'),
    ('expenses', 'ptcl/telephone expense', 'Expenses', 'Ptcl/Telephone Expense'),
    ('expenses', 'refreshment', 'Expenses', 'Refreshment'),
    ('expenses', 'registration & regulatory fees', 'Expenses', 'Registration & Regulatory Fees'),
    ('expenses', 'repair & maintenance', 'Expenses', 'Repair & Maintenance'),
    ('expenses', 'repair and maintenance', 'Expenses', 'Repair & Maintenance'),
    ('expenses', 'repairs & maintenance', 'Expenses', 'Repairs & Maintenance'),
    ('expenses', 'salaries', 'Expenses', 'Salaries'),
    ('expenses', 'salary', 'Expenses', 'Salaries'),
    ('expenses', 'security guard', 'Expenses', 'Security Guard'),
    ('expenses', 'security guard salary', 'Expenses', 'Security Guard Salary'),
    ('expenses', 'society share', 'Expenses', 'Society Share'),
    ('expenses', 'staff final settlement', 'Expenses', 'Staff Final Settlement'),
    ('expenses', 'staff salary', 'Expenses', 'Salaries'),
    ('expenses', 'staff welfare & grants', 'Expenses', 'Staff Welfare & Grants'),
    ('expenses', 'stationery & printing', 'Expenses', 'Stationery & Printing'),
    ('expenses', 'stationery expense', 'Expenses', 'Stationery Expense'),
    ('expenses', 'sui gas charges', 'Expenses', 'Sui Gas Charges'),
    ('expenses', 'sui gas expense', 'Expenses', 'Sui Gas Expense'),
    ('expenses', 'telephone bills', 'Expenses', 'Telephone Bills'),
    ('expenses', 'utilities', 'Expenses', 'Utilities'),
    ('expenses', 'utility', 'Expenses', 'Utility'),
    ('expenses', 'vehicle fuel & generator expense', 'Expenses', 'Vehicle Fuel & Generator Expense'),
    ('expenses', 'w.h tax', 'Expenses', 'W.H Tax'),
    ('expenses', 'water expense', 'Expenses', 'Water Expense'),
    ('income', 'admission fee', 'Income', 'Admission Fee'),
    ('income', 'admission fee income', 'Income', 'Admission Fee Income'),
    ('income', 'admission form fee', 'Income', 'Admission Form Fee'),
    ('income', 'admission form sales', 'Income', 'Admission Form Sales'),
    ('income', 'annual charges', 'Income', 'Annual Charges'),
    ('income', 'annual charges income', 'Income', 'Annual Charges Income'),
    ('income', 'bank profit', 'Income', 'Bank Profit'),
    ('income', 'bus / transport fee', 'Income', 'Bus / Transport Fee'),
    ('income', 'bus fee income', 'Income', 'Bus Fee Income'),
    ('income', 'canteen rent', 'Income', 'Canteen Rent'),
    ('income', 'canteen rent income', 'Income', 'Canteen Rent Income'),
    ('income', 'fine / late fee income', 'Income', 'Fine / Late Fee Income'),
    ('income', 'fine income', 'Income', 'Fine Income'),
    ('income', 'miscellaneous income', 'Income', 'Miscellaneous Income'),
    ('income', 'miscellaneous/installment income', 'Income', 'Miscellaneous/Installment Income'),
    ('income', 'monthly fee income', 'Income', 'Monthly Fee Income'),
    ('income', 'monthly fund income', 'Income', 'Monthly Fund Income'),
    ('income', 'monthly funds', 'Income', 'Monthly Funds'),
    ('income', 'registration fee', 'Income', 'Registration Fee'),
    ('income', 'registration fee income', 'Income', 'Registration Fee Income'),
    ('income', 'rent income', 'Income', 'Rent Income'),
    ('income', 'security fee income', 'Income', 'Security Fee Income'),
    ('income', 'tuition fee (monthly fee)', 'Income', 'Tuition Fee (Monthly Fee)'),
    ('income', 'tuition fee income', 'Income', 'Tuition Fee Income'),
    ('income', 'tuition fee recievable', 'Income', 'Tuition Fee Recievable'),
    ('liabilities', 'cpf', 'Accrued and Other Liabilities', 'CPF'),
    ('liabilities', 'eobi', 'Accrued and Other Liabilities', 'EOBI'),
    ('liabilities', 'fee refund', 'Accrued and Other Liabilities', 'Fee Refund'),
    ('liabilities', 'ibft from other campuses', 'Accrued and Other Liabilities', 'IBFT From Other Campuses'),
    ('liabilities', 'income tax exp', 'Accrued and Other Liabilities', 'Income Tax Exp'),
    ('liabilities', 'income tax payable', 'Accrued and Other Liabilities', 'Withholding Tax/Income Tax Payable'),
    ('liabilities', 'inter-campus loan payable', 'Accrued and Other Liabilities', 'Inter-Campus Loan Payable'),
    ('liabilities', 'pessi', 'Accrued and Other Liabilities', 'PESSI'),
    ('liabilities', 'salary', 'Accrued and Other Liabilities', 'Salaries'),
    ('liabilities', 'security deposit refund', 'Accrued and Other Liabilities', 'Security Deposit Refundable'),
    ('liabilities', 'security guard', 'Accrued and Other Liabilities', 'Security Guard'),
    ('liabilities', 'utility', 'Accrued and Other Liabilities', 'Utility'),
    ('liabilities', 'wht payable', 'Accrued and Other Liabilities', 'Withholding Tax/Income Tax Payable'),
    ('non- current assets', 'work in progress - building and civil works', 'Non-Current Assets', 'Work In Progress - Building And Civil Works'),
    ('non-current asset', 'building improvements - additions', 'Non-Current Assets', 'Building Improvements - Additions'),
    ('non-current assets', 'building improvements - additions', 'Non-Current Assets', 'Building Improvements - Additions'),
    ('requires clarification', 'outward clearing (inter-account)', 'Requires Clarification', 'Outward Clearing (Inter-Account)'),
    ('requires clarification', 'unidentified cash deposit', 'Requires Clarification', 'Unidentified Cash Deposit'),
    ('requires clarification', 'unidentified payment', 'Requires Clarification', 'Unidentified Payment'),
    ('requires clarification', 'unidentified receipt', 'Requires Clarification', 'Unidentified Receipt')
) as v(alias_main, alias_sub, main_head, sub_head)
join public.account_heads h on h.main_head = v.main_head and h.sub_head = v.sub_head;
